[tool.briefcase]
project_name = "Bottle Single Page Application"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/bottle_spa"
license = "MIT license"
author = 'MilkUI'
author_email = "milkui@example.com"

[tool.briefcase.app.bottle_spa]
formal_name = "Bottle Single Page Application"
description = "Bottle single page application example"
icon = "src/bottle_spa/resources/bottle_spa"
sources = ['src/bottle_spa']
requires = [
    'bottle'
]


[tool.briefcase.app.bottle_spa.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.bottle_spa.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.bottle_spa.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.bottle_spa.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.bottle_spa.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
